format: xs-configuration-v2
files:
  workspace: "/xs-workspace.yaml"
  tsconfig: "/tsconfig.json"
scriptsNames:
  buildMicroFrontend: "build-microfrontend"
  cacheSynchronization: "cache-synchronization"
  buildBootstrap: "build-bootstrap"
hosts:
  ipfsNode: "ipfs-api.solenopsys.org:80"
  pinningService: "http://pinning.solenopsys.org"
  helmRepository: "http://helm.solenopsys.org"
templates:
  sections:
    converged: "@solenopsys/pl-tp-converged" # все что связано с ui
    shockwaves: "@solenopsys/pl-tp-shockwaves" # все что связано c хранением и обработкои данных
    combinatorics: "@solenopsys/pl-tp-combinatorics" # все что связано с физическими устройствами
    synthetic: "@solenopsys/pl-tp-synthetic" # блокчейн и смарт контракты
    matrix: "@solenopsys/pl-tp-matrix" # все что связано со стандартами и соглашениями
    platform: "@solenopsys/pl-tp-platform" # все что связано с платформой
  creation: {}
git:
  paths:
    # converged
    bootstraps: converged/bootstraps
    frontlibs: converged/libraries
    uimatrix: converged/libraries
    microfrontends: converged/microfrontends
    # shockwaves
    backlibs: shockwaves/libraries
    deployments: shockwaves/deployments
    microservices: shockwaves/microservices
    dataservices: shockwaves/dataservices
    microkernels: shockwaves/microkernels
    # combinatorics
    firmware: combinatorics/firmware
    electronic: combinatorics/electronic
    engineering: combinatorics/engineering
    # synthetic
    contracts: synthetic/contracts
    chains: synthetic/chains
    # platform
    templates: platform/templates
    tools: platform/tools
    content: platform/content
    generators: platform/generators
    # matrix
    standards: matrix/standards

  prefixes:
    bs: bootstraps
    fl: frontlibs
    ui: uimatrix
    mf: microfrontends
    tl: tools
    tp: templates
    bl: backlibs
    dp: deployments
    ms: microservices
    ds: dataservices
    mc: microkernels
    ct: content
    st: standards
    fw: firmware
    el: electronic
    en: engineering
    cn: contracts
    ch: chains
    gn: generators
jobs:
  builders:
    bootstrap:
      - frontends/bootstraps
    microfrontend:
      - frontends/modules
    frontlib:
      - frontends/libraries
    helm:
      - backends/deployments
    backlib:
      - backends/libraries
    container:
      - backends/modules
  processors:
    ts_injector:
      description: Injects source code location to tsconfig.json file
      triggers:
        - type: post
          sections:
            - frontends
          command:
            - code
            - add
    ts_remover:
      description: Remove source code location from tsconfig.json file
      triggers:
        - type: post
          sections:
            - frontends
          command:
            - code
            - remove