format: xs-configuration-v2
files:
  workspace: "/xs-workspace.yaml"
  tsconfig: "/tsconfig.json"
hosts:
  ipfsNode: "ipfs-api.solenopsys.org:80"
  pinningService: "http://pinning.solenopsys.org"
  helmRepository: "http://helm.solenopsys.org"
templates:
  sections:
    frontends: "@solenopsys/tp-frontends"
    backends: "@solenopsys/tp-backends"
    tools: "@solenopsys/tp-tools"
    contracts: "@solenopsys/tp-contracts"
    embedded: "@solenopsys/tp-embedded"
    engineering: "@solenopsys/tp-engineering"
  creation: {}
git:
  paths:
    bootstraps: frontends/bootstraps
    frontlibs: frontends/libraries
    uimatrix: frontends/libraries
    microfrontends: frontends/modules
    tools: tools
    templates: templates
    backlibs: backends/libraries
    deployments: backends/deployments
    microservices: backends/modules
  prefixes:
    bs: bootstraps
    fl: frontlibs
    ui: uimatrix
    mf: microfrontends
    tl: tools
    tp: templates
    bl: backlibs
    dp: deployments
    ms: microservices
jobs:
  builders:
    bootstrap:
      - frontends/bootstraps
    microfrontend:
      - frontends/modules
    frontlib:
      - frontends/libraries
    helm:
      - backends/deployments
    backlib:
      - backends/libraries
    container:
      - backends/modules
  processors:
    ts_injector:
      description: Injects source code location to tsconfig.json file
      triggers:
        - type: post
          sections:
            - frontends
          command:
            - code
            - add
    ts_remover:
      description: Remove source code location from tsconfig.json file
      triggers:
        - type: post
          sections:
            - frontends
          command:
            - code
            - remove